### PR TITLE
Refuse to connect with faces of a node which are not marked valid

### LINKED ISSUE #4: New feature: Ability to disable the sides of certain nodes from connecting with tubes
This is part of the fix for this issue https://github.com/joe7575/techpack/issues/67

I thought the best way to do this was to add a new feature to tubelib, that would allow you to describe which faces of a node can and cannot be connected to with a tube.

There are several ways this could be done:
- Use a list of allowed directions
- Use a list of disallowed directions
- Use a flag like "face only", which can then be used with param2 to disallow other faces from connecting

### PR DESCRIPTION
**Pull request by oversword**
Fixes #4 

This is required to fix https://github.com/joe7575/techpack/issues/67

This looks for a `'valid_dirs'` metadata attribute for secondary nodes, and checks if the dir that is trying to connect to them is valid. If no metadata is given, it defaults to `Tube.valid_dirs`, which lists all dirs

This might not be the best way to go about this, as mentioned in issue #4 there are several other ways we could achieve this, but event for this method I'm not sure it's the best way to code it.
We could:
- Create another function (or just a loop), separate from `get_secondary_node` that performs this check exclusively
- Used something other than metadata - I'm not 100% sure metadata is the best / only way to get this kinda data down to the internal functions

### CODE REVIEW

**Comment by oversword** [comment]
Sorry @joe7575 I'm going to need to redo this, I don't think this solution is very good, I just noticed that the metadata does not persist after the game is restarted, this can be achieved by adding a get_staticdata and on_activate callback to the nodes, but that would mean each invocation of this new feature would require custom code to do that.
Here's what I think is a better solution:
Each type of node defines a "valid_face" callback that takes the param2 and direction as arguments, returning true or false if the face is valid

This removes the reliance on every node remembering which faces are valid.

I came up with this because I realised that, although tubes have been fixed, you can still use a pusher to inject things directly into a node (in this case the teleporter). I found this metadata issue while testing that.

**Comment by joe7575** [comment]
New Idea (completely untested, from brain into GitHub):

```lua
-- We could introduce the 'sides' from tubelib (TechPack):

                       Up    Back
                        |    /
                        |   /
                     +--|-----+
                    /   o    /|
                   +--------+ |
          Left ----|        |o---- Right
                   |    o   | |
                   |   /    | +
                   |  /     |/
                   +-/------+
                    /   |
                 Front  |
                        |
                      Down


-- This would allow the additional parameter 'valid_sides' for 'add_secondary_node_names'
function Tube:add_secondary_node_names(names, valid_sides)
	for _,name in ipairs(names) do
		self.secondary_node_names[name] = 
				valid_sides or {B=true, R=true, F=true, L=true, D=true, U=true}
	end
end

-- With copied from tubelib/command.lua...
local DirToSide = {"B", "R", "F", "L", "D", "U"}

local function dir_to_side(dir, param2)
	if dir < 5 then
		dir = (((dir - 1) - (param2 % 4)) % 4) + 1
	end
	return DirToSide[dir]
end

-- ...the modified `get_secondary_node` function could look like:
function Tube:get_secondary_node(pos, dir)
	local npos = vector.add(pos, Dir6dToVector[dir or 0])
	local node = self:get_node_lvm(npos)
	if self.secondary_node_names[node.name] then
		local side = dir_to_side(dir, node.param2)
	        local is_valid_dir = self.secondary_node_names[node.name][side] or false
		return node, npos, is_valid_dir
	end
end
```

**Comment by oversword** [comment]
I fixed the pusher issue independently of this re-structure issue https://github.com/joe7575/techpack/pull/73

As long as we're just modifying how get_secondary_node determines if a face is valid or not that code should work fine

I will read through your proposal now, I have also managed to come up with something better (than the current metadata solution) but haven't pushed anything yet

**Comment by oversword** [comment]
FYI my solution was to basically do this:
```
		local valid = true
		if odir ~= nil and minetest.registered_nodes[node.name].valid_face then
			if false == minetest.registered_nodes[node.name].valid_face(npos, node.param2, odir) then
				valid = false
			end
		end
```

inside `get_secondary_node`, where `valid_face` is the function I described previously (returns boolean, takes directional arguments)

I was originally thinking this would be like `on_pull_item`, but of course `tubelib.register_node` is part of the tubelib implementation, not this generic base module

**Comment by oversword** [comment]
@joe7575 Okay I think I understand your solution, that probably is the best way to go. I'm not sure we _need_ sides to be defined in the tubelib base module, but it certainly would make defining the valid sides more intuitive.

I'll write this up and implement :+1:

**Comment by oversword** [comment]
@joe7575 written these up
https://github.com/joe7575/tubelib2/pull/8
https://github.com/joe7575/techpack/pull/74

Will focus on the pusher issue now, I'd rather not merge these until I'm certain it will help us solve this problem for good, but please feel free to review & test

**Pull request merged**
